### ISSUE TITLE
Longhorn volumes path /tmp/longhorn doesn't persist across reboots

### ISSUE THREAD

**Issue by fcastello** [balchua/do-microk8s#2]
Hi,
Following this guide with installing longhorn I experienced something weird.
From this doc https://github.com/balchua/do-microk8s/blob/master/docs/longhorn.md
The following has a caveat
```microk8s helm3 install longhorn longhorn/longhorn --namespace longhorn-system \
  --set defaultSettings.defaultDataPath="/tmp/longhorn" \
  --set csi.kubeletRootDir="/var/snap/microk8s/common/var/lib/kubelet"
```

Specially the flag `--set defaultSettings.defaultDataPath="/tmp/longhorn" `

It's a bit dangerous if you want to do something serious with the cluster.

I ran this in an ubuntu server and everything went smoothly until I restarted 1 node and the node became unavailable in longhorn. I had to rebuild the node to fix it. Then happened to a second node. Then I decided to restart all nodes just for testing and voila, lost all my volumes.

Then I realized longhorn is saving the volumes in /tmp/longhorn. But ubuntu after restart clears everything in /tmp
I might submit a Pull Request with a fix with a different path. So it doesn't happen to anyone else.
I solved it by using /longhorn in that flag.

**Comment by balchua** [comment]
Thanks for highlighting that one. ,👍

**Comment by fcastello** [comment]
@balchua I added a simple PR that changes the longhorn in the longhorn guide 
https://github.com/balchua/do-microk8s/pull/3

**Comment by balchua** [comment]
Thanks @fcastello for spotting this one.
